spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Review
          uri: http://localhost:8080
          predicates:
            - Path=/reviews/** 
        - id: Movie
          uri: http://localhost:8080
          predicates:
            - Path=/movies/** 
        - id: Notice
          uri: http://localhost:8080
          predicates:
            - Path=/notices/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

api:
  url:
    payment: http:/localhost/:8080

server:
  port: 8080
---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Review
          uri: http://Review:8080
          predicates:
            - Path=/reviews/** 
        - id: Movie
          uri: http://Movie:8080
          predicates:
            - Path=/movies/** 
        - id: Notice
          uri: http://Notice:8080
          predicates:
            - Path=/notices/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

api:
  url:
    payment: http://moviereviews:8080

server:
  port: 8080
---